### ISSUE TITLE
[OnlineMeeting]2.0 core framework discuss

### ISSUE THREAD

**Issue by CalvinKirs** [apache/incubator-seatunnel#1010]
CalvinKirs invites you to a meeting on Tencent Meeting
Meeting Topic: 2.0 new feature discuss
Meeting Time: 2022/01/13 20:00-21:00 (GMT+08:00) China Standard Time - Beijing

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/aohefsAbAzCS

#TencentMeeting：188-997-480

Copy this invitation and open in Tencent Meeting app (V2.13 or later) to join the meeting

discuss issue:
- [ ] #834 
- [x] #788 
- [ ] #962 
- [ ] #963 
- [ ] #964 
- [ ] #965 
- [ ] #875

**Comment by CalvinKirs** [comment]
If you have other questions to discuss, please create an issue and leave a message.

**Comment by zhongjiajie** [comment]
@CalvinKirs Maybe we need special labels for issues like that, cause we may have lots of related issues in the further. With label make the user easy to track our meeting context

**Comment by wuchunfu** [comment]
hi @CalvinKirs [[Feature]support latest version of Spark 3.2.0](https://github.com/apache/incubator-seatunnel/issues/875) Should this be discussed?

**Comment by CalvinKirs** [comment]
> hi @CalvinKirs [[Feature]support latest version of Spark 3.2.0](https://github.com/apache/incubator-seatunnel/issues/875) Should this be discussed?

true,add~

**Comment by CalvinKirs** [comment]
> hi @CalvinKirs, add a topic -> `Integrate docs to https://github.com/apache/incubator-seatunnel-website`
> 
> e.g https://github.com/apache/hudi/tree/asf-site https://github.com/apache/dolphinscheduler-website



> hi @CalvinKirs, add a topic -> `Integrate docs to https://github.com/apache/incubator-seatunnel-website`
> 
> e.g https://github.com/apache/hudi/tree/asf-site https://github.com/apache/dolphinscheduler-website

I took a preliminary look and it seems that `hudi` maintains a branch in the code repository to manage the website, is that so?
What we need to do is similar to `skywalking`, functional technical documents are managed in the code warehouse, and the official website deploys and parses the code warehouse.

**Comment by CalvinKirs** [comment]
> hi @CalvinKirs, add a topic -> `Integrate docs to https://github.com/apache/incubator-seatunnel-website`
> 
> e.g https://github.com/apache/hudi/tree/asf-site https://github.com/apache/dolphinscheduler-website

Can you add an issue first? Then I will link the issue.

**Comment by Narcasserun** [comment]
I would like to ask a question, support multi-engine computing, and unify DSL. The goal is definitely not to let users call Spark/Flink APIs and continue to write spark/flink jobs, it should be to make users do not need to understand Spark/flink logic and lower the threshold for use. What is the main difference between this and some of the `serverless `platforms? The core module implementation seems to be similar

**Comment by CalvinKirs** [comment]
closed
