### ISSUE TITLE
[Bug] [startup script] lost plugins directory cause start script error

### ISSUE THREAD

**Issue by yx91490** [apache/incubator-seatunnel#1023]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

startup script show error plugins directory not found

### SeaTunnel Version

2.0.5

### SeaTunnel Config

```conf
No
```

### Running Command

```shell
general
```

### Error Exception

```log
plugins directory not found
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leo65535** [comment]
cc @CalvinKirs, seems we need revert the plugins folder, and remove all other useless files in it, like `.gitee`

**Comment by CalvinKirs** [comment]
> cc @CalvinKirs, seems we need revert the plugins folder, and remove all other useless files in it, like `.gitee`

I revitd, PTAL #1027 :)

**Comment by leo65535** [comment]
+1, thanks @CalvinKirs
