### ISSUE TITLE
[Bug] [mysql sink] 解析kafka数据写入mysql失败但未打印错误信息

### ISSUE THREAD

**Issue by JustinMars1** [apache/incubator-seatunnel#1024]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

解析kafka数据写入mysql失败但未打印错误信息
1.MySQL建表语句（test数据库）
CREATE TABLE `nn` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `created` date DEFAULT NULL,
  `modified` date DEFAULT NULL,
  `yn` int(11) DEFAULT NULL
)；
2.创建kafka生产者，生产信息如下
>1,justin
>2.mars
3.使用打印信息的方式数据是显示的
如
sink {
  console {}
}
输出信息如下
+---+------+
|id |name  |
+---+------+
|1  |justin|
+---+------+
4.使用mysql配置信息，未写入数据库，也为打印错误日志

### SeaTunnel Version

waterdrop-dist-2.0.4-2.11.8

### SeaTunnel Config

```conf
env {
  # seatunnel defined streaming batch duration in seconds
  spark.streaming.batchDuration = 5

  spark.app.name = "seatunnel"
  spark.ui.port = 13000
}

source {
  kafkaStream {
    topics = "seatunnel"
    consumer.bootstrap.servers = "bigdata2:9092"
    consumer.group.id = "seatunnel_group_mysql1"
    auto.offset.reset = "latest"
   }
}

transform {
  split {
    source_field = "raw_message"
    delimiter = ","
    fields = ["id","name"]
    result_table_name = "mars"
  }
  sql {
    sql = "select id,name from mars",
    table_name = "mars"
  }
}

sink {
  Mysql {
    save_mode = "update",
    truncate = true,
    url = "jdbc:mysql://ip:3306/test",
    user= "root",
    password = "*****",
    dbtable = "mars",
    customUpdateStmt = "INSERT INTO test.nn (id, name, created, modified, yn) values(?, ?, now(), now(), 1) ON DUPLICATE KEY UPDATE id = IFNULL(VALUES (id), id), name = IFNULL(VALUES (name), name)"
}
}
```

### Running Command

```shell
./bin/start-waterdrop-spark.sh --master local[4] --deploy-mode client --config ./config/sparkkafkamysql.conf
```

### Error Exception

```log
未打印错误信息，但也为写入mysql数据库
```

### Java or Scala Version

jdk 1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JustinMars1** [comment]
dbtable = "mars"使用nn,也是数据未入库

**Comment by CalvinKirs** [comment]
For better communication, please describe your problem in English, I will close this issue, you can reopen it when you are done updating.

**Comment by JustinMars1** [comment]
> For better communication, please describe your problem in English, I will close this issue, you can reopen it when you are done updating.

already edit
