### ISSUE TITLE
[Feature][seatunnel 1.x plugin-filter-join] Join filter support join type

### ISSUE THREAD

**Issue by TyrantLucifer** [apache/incubator-seatunnel#1046]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Join filter plugin support that can assign join type in conf, currently join type had been hard code in seatunnel

### Usage Scenario

When we want to join two tables, we can change the join type between two tables in conf file, for example:

join {
  join_type = left
}

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RickyHuo** [comment]
You can use filter `sql` directly. The filter of `join` seem useless.

**Comment by TyrantLucifer** [comment]
Get it. Thank you for your reply. I will close this issue.
