### ISSUE TITLE
[Feature][Plugin] Add Plugin Flink Source Mysql CDC

### ISSUE THREAD

**Issue by chaozwn** [apache/incubator-seatunnel#1068]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

support seatunnel connector to Mysql cdc Source.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
We cannot integrate due to license reasons

**Comment by JesseAtSZ** [comment]
I want to realize this function, can I reopen the issue ？

**Comment by JesseAtSZ** [comment]
Anybody here?

**Comment by CalvinKirs** [comment]
> I want to realize this function, can I reopen the issue ？

Do you have any other way? Does not introduce mysql dependencies.

**Comment by JesseAtSZ** [comment]
> > I want to realize this function, can I reopen the issue ？
> 
> Do you have any other way? Does not introduce mysql dependencies.

Can CDC be implemented in this way?
![image](https://user-images.githubusercontent.com/35264598/155247494-f5ee6c91-2d3d-4db9-a3f1-a2193e29b9e9.png)

**Comment by CalvinKirs** [comment]
No, he depends on mysql

**Comment by JesseAtSZ** [comment]
> No, he depends on mysql

I just looked at the license of flick CDC connectors, which is Apache License2. Can you explain why this license is not OK?
