### ISSUE TITLE
文档丰富计划

### ISSUE THREAD

**Issue by garyelephant** [apache/incubator-seatunnel#210]
* README/Index
  * Waterdrop 简易架构图
  * Waterdrop 与Spark的关系图

* 知识普及
  * 帮助用户减少对Spark的恐惧、不熟悉、觉得太复杂，让Spark变得简单。
  * Spark Standalone集群如何搭建的简化版本。

* 线上应用实践案例
   * 多数据源处理（比如HDFS, ES 多源关联处理）
   * 流和维表关联
   * 全流程SQL处理
   *  waterdrop + azkaban/oozie

* 插件文档
   * convert 替换为用sql做类型转换

* Waterdrop 运行流程介绍
   * 清楚明晰的的介绍waterdrop的核心概念，功能，架构。
   * 多Pipeline

* 配置
   * 多pipeline
   * 动态变量替换
   * input kafka
   * input hive

* 插件开发
  * StreamingInput API发生变更[同时更新example project]
  * 自定义插件，的配置中插件名的命名方式: `com.xx.customfilter -> com_xx_customfilter`
  * META 配置是必须的。

* 深入Waterdrop
  * 在IDEA中，编译运行，报Configparser, Antlr4相关错误

* Roadmap

**Comment by garyelephant** [comment]
流和维表关联：


现在流和静态维表关联是支持的，如果维表存在hdfs，mysql，可以直接用hdfs input插件，或者mysql input插件，注册为table，直接与流关联即可。

![image](https://user-images.githubusercontent.com/2291859/50580896-51fa9680-0e8f-11e9-925c-74692de00f66.png)

**Comment by wanglaichao** [comment]
文档有个问题，插件开发那里注册udf 的process那里代码不会执行的 有点误导作用

**Comment by garyelephant** [comment]
convert 替换为用sql做类型转换：

```
比如：
sql {
   sql = "select to_date(chargeTime, 'yyyy-MM-dd')as chargeTime, * from table1"
   table_name = "table1"
}

这里有一些spark sql 时间相关的udf：https://blog.csdn.net/u014589856/article/details/80347917

另外，其实所有字段的类型转换，都可以在一个sql里面完成。


```

**Comment by garyelephant** [comment]
@wanglaichao 抱歉没明白，能加一下我的微信(`garyelephant`)说一下吗

**Comment by garyelephant** [comment]
流式表，静态维度表关联配置举例：

```
spark {
  ......
}

input {
 ## 这个是流水的input
 kafkaStream {
  ...
 }

 ## 这个是静态的input，加载数据后，注册为表"dict_table"
 hdfs {
   path = "/path/to/dimension_table/table1.txt"
   format = "json"
   table_name = "dict_table"
 }

}

filter {
  ## 通过SQL将流式表和静态维度表关联到一起。
  sql {
    table_name = "streamtable"
    sql = "select streamtable.*, dict_table.city_name from streamtable join dict_table where streamtable.city_code = dict_table.city_code"
  }
}

output {
  stdout {}
}

```

**Comment by garyelephant** [comment]
问题：在IDEA中，编译运行，报Configparser, Antlr4相关错误
解决方法：需要在IDEA中配置一下，

把这个目录mark as generated source root,

<img width="1100" alt="generated_source_root" src="https://user-images.githubusercontent.com/2291859/53925389-cc77aa80-40ba-11e9-89e1-1ba0336f582b.png">

**Comment by garyelephant** [comment]
input kafka OOM 问题：

![image](https://user-images.githubusercontent.com/2291859/54007792-94e22e80-419e-11e9-9ea3-51a87c6c1a6b.png)


spark中需要再增加一个配置，

```
spark {
    spark.streaming.kafka.maxRatePerPartition = 100
}
```

 , 这个参数的缺失，极有可能是你OOM的最主要的原因:这个参数是做限流的，如果不限流就很容易oom

至于这个数字配置成多少，需要根据以下3个因素来确定：
（1）平均每个core的处理能力
（2）kafka topic有多少partition
（3）spark.executor.cores * spark.executor.instances 你分配了多大资源

**Comment by garyelephant** [comment]
input hive 连不上的问题：

**Comment by garyelephant** [comment]
Structured Streaming相关文档更新：

* @kid-xiong   structured streaming应用案例

* structured streaming使用方法介绍

* structured streaming功能加入后，插件配置文档复杂了很多，而且也不清晰比如kafkaStream Input, kafka Output 的文档：是表达方式需要优化，还是对Structured Streaming中各种高级概念的不理解？为了简化文档，需要对不同的engine做更明显的区分。

* Structured Streaming中各种高级概念的解释。

* 插件开发（+ structured streaming）

**Comment by pdlovedy** [comment]
在waterdrop对于es的读取中（es作为input插件）【https://interestinglab.github.io/waterdrop-docs/#/zh-cn/v1/configuration/input-plugins/Elasticsearch】，加上对es configuration参数的说明，用以最大化waterdrop读取es的效率，该参数为：es.input.max.docs.per.partition的值如下：分区数 = 总数据条数/es.input.max.docs.per.partition。让用户选择合适的分区数，用以处理可能数据量较大时带来的shuffle过长使得es与其他组件迁移速率低下的问题。也是通过控制读取es的分区数来加快shuffle的过程，添加说明可以使得用户更加方便高效。
