### ISSUE TITLE
[plugin] MySQL Binlog StreamingInput

### ISSUE THREAD

**Issue by garyelephant** [apache/incubator-seatunnel#233]
https://github.com/shyiko/mysql-binlog-connector-java
https://segmentfault.com/a/1190000016679734#articleHeader3
https://codeday.me/news/20170617/20509.html
http://blog.51cto.com/6226001001/1672159
https://cloud.tencent.com/developer/article/1032755
https://juejin.im/entry/5b7642e8e51d45664153b447
http://www.ywnds.com/?p=12839

**Comment by garyelephant** [comment]
https://github.com/alibaba/canal

除了支持存量同步，还需要支持增量订阅binlog（存在CRUD操作，需要注意顺序）的同步

**Comment by garyelephant** [comment]
+1

**Comment by RickyHuo** [comment]
https://medium.com/@williamsmith_74955/how-spark-binlog-works-323c16fb1498

**Comment by garyelephant** [comment]
duplicate of #963

**Comment by tmljob** [comment]
Due to various acquisition requirements, our acquisition framework plans to integrate DataX, canal, and flume, but I have seen that seatunnel supports integrated streaming and batch processing. Is it possible to use seatunnel without integrating other frameworks?
