### ISSUE TITLE
针对jdbc的output提供merge的savemode

### ISSUE THREAD

**Issue by cmdares** [apache/incubator-seatunnel#249]
如题：
主要想对于oracle、postgresql、mysql提供merge的保存方式。
可以考虑使用原生的方法进行操作，性能最高。
merge：即入库时候根据主键进行比对，如果重复，则进行更新，如果不重复则进行插入。
oracle: https://blog.csdn.net/jeryjeryjery/article/details/70047022
postgresql:https://yq.aliyun.com/articles/655509
mysql:https://blog.csdn.net/liuabc0719/article/details/37039309
可以参考这三大主流数据库的merge方法。
感谢！
参考一下 confluent 的kafka处理平台类似的功能：
https://docs.confluent.io/current/connect/kafka-connect-jdbc/sink-connector/index.html#idempotent-writes

**Comment by garyelephant** [comment]
感谢提供反馈，请加微信`garyelephant`, 方便进一步满足你的需求。
