### ISSUE TITLE
[Bug] 多个output不能并行

### ISSUE THREAD

**Issue by garyelephant** [apache/incubator-seatunnel#400]
当配置多个output时，其对应的spark job不能并行：

```
...
output {
  xxx {}
  yyy {}
}
```

其中 xxx, yyy 不能并行。

@RickyHuo 支持一下这个功能，然后发一个新版吧。

**Comment by garyelephant** [comment]
另外，对Waterdrop的pipeline有了新的理解，比如如何支持数据输出后校验，可以这样做，按顺序启动两个waterdrop，一个负责迁移数据，一个负责做count检验，这两个在配置里面写sql应该都能搞定。

也就是说output不一定是终点，input也不一定是起点。所以目前看，flink sql client的交互式客户端可能更灵活一点。

**Comment by RickyHuo** [comment]
是否并行应该让用户配置？
