### ISSUE TITLE
支持oracle并发读取

### ISSUE THREAD

**Issue by cmdares** [apache/incubator-seatunnel#416]
可以利用oracle原生ora_hash(rowid,4)=1，2，3，4 进行并发搬迁，提高速度，切分相当均匀。当时使用自己改造的datax，速度相当快，已经用于生产。
这个语句是通过观测ibm的datastage后台发现的，可以把思路借来用用。
希望提供到waterdrop

**Comment by garyelephant** [comment]
@cmdares 你好，可以为waterdrop贡献一个oracle的input插件吗
