### ISSUE TITLE
Tidb Input improvement

### ISSUE THREAD

**Issue by ludengke95** [apache/incubator-seatunnel#439]
1. SPARK>=2.3，waterdrop让下载1.4.2，TiSpark2.0+才支持spark2.3，并且TiSpark2.0+仅支持TiDB3.0+，看看工程build.sbt，TiSpark才1.1版本， 使用过程中各种BUG，spark-shell + TiSpark2.0感觉都比其中tidb模块好用。
2. 插件开发的文档里面貌似少东西吧，我没看到任何一个地方写明自定义插件名称在配置文件要以全路径类名的引用。

**Comment by ludengke95** [comment]
希望作者不要介意，我说话比较直。

**Comment by ludengke95** [comment]
能打包一个tispark是2.2.0的版本的么？我本地打包了好几次都是失败了。

**Comment by RickyHuo** [comment]
@ludengke95 

Tidb 插件开发距今已经一年，期间没有人反馈过问题，首先感谢你的反馈，督促我们优化。

1. Tidb插件开发是基于 Waterdrop 1.1.5，相关中文文档里面写明了仅支持 spark 2.1，后续我们的相关更新可能忽略了相关说明。
2. 插件开发使用第三方插件，我们可能默认大家都会使用全路径类名，因此只在demo中使用了自定义插件全路径类名，这是我们的疏忽。

**Comment by RickyHuo** [comment]
使用 、编译如果还有问题，可以微信联系我 chodomatte1994

**Comment by ludengke95** [comment]
谢谢作者能够回答，这是我写的插件，你可以看一下。https://github.com/ludengke95/waterdrop-tidb2-plugin

**Comment by ludengke95** [comment]
> 使用 、编译如果还有问题，可以微信联系我 chodomatte1994



> @ludengke95
> 
> Tidb 插件开发距今已经一年，期间�没有人反馈过问题，首先感谢你的反馈，督促我们优化。
> 
> 1. Tidb插件开发是基于 Waterdrop 1.1.5，相关中文文档里面写明了仅支持 spark 2.1，后续我们release changelog 的相关更新可能忽略了相关说明。
> 2. 插件开发使用第三方插件，我们可能默认大家都会使用全路径类名，因此只在demo中使用了自定义插件全路径类名，这是我们的疏忽。

谢谢作者能够回答，这是我写的插件，你可以看一下。https://github.com/ludengke95/waterdrop-tidb2-plugin

**Comment by garyelephant** [comment]
@ludengke95 感谢，我们把这个插件放到插件包里？@RickyHuo

**Comment by ludengke95** [comment]
> @ludengke95 感谢，我们把这个插件放到插件包里？@RickyHuo

你们测试通过之后，可以放在插件包里。前提，更新下tispark到2.0+版本。
