### ISSUE TITLE
Do not need to log user && password when running

### ISSUE THREAD

**Issue by mkdym** [apache/incubator-seatunnel#491]
**Waterdrop Version(Waterdrop版本)**
1.4.3

**Spark Version(Spark 版本)**
2.4.5

**Java Version(Java版本)**
1.8

**context**
User accounts of data sources, which are always configured in waterdrop task config file, are sensitive infomation.
But waterdrop logs the entire config file without data desensitization when running.
Because of this, I can't integrate waterdrop with other task scheduler which will grab the output to display.

I think, waterdrop can log sensitive infomation as ****** , instead of plain text.

**Comment by 17625939872** [comment]
+1
