### ISSUE TITLE
写入ck配置了 3次重试，怎么一次进程就挂掉了

### ISSUE THREAD

**Issue by javalover123** [apache/incubator-seatunnel#543]
**Waterdrop Version(Waterdrop版本)**

1.4.1

**Flink or Spark Version(Flink 或者 Spark 版本)**

spark-2.4.0-bin-hadoop2.7

**Java or Scala Version(Java或者Scala版本)**

java 1.8

**Waterdrop Config(Waterdrop配置文件)**

```
######
###### This config file is a demonstration of streaming processing in waterdrop config
######

spark {
  # You can set spark configuration here
  # Waterdrop defined streaming batch duration in seconds
  spark.streaming.batchDuration = 5

  # see available properties defined by spark: https://spark.apache.org/docs/latest/configuration.html#available-properties
  spark.app.name = "Waterdrop"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
}

input {
  # This is a example input plugin **only for test and demonstrate the feature input plugin**

  kafkaStream {
    topics = "topic"
    result_table_name = "topic_kafka"
    consumer.bootstrap.servers = "host:8082"
    consumer.group.id = "waterdrop-topic"
    consumer.rebalance.max.retries = 100
    consumer.failOnDataLoss = false
  }

  # If you would like to get more information about how to configure waterdrop and see full list of input plugins,
  # please go to https://interestinglab.github.io/waterdrop/#/zh-cn/configuration/base
}

filter {

  json {
    source_field = "raw_message"
    result_table_name = "topic"
  }

  remove {
    source_field = ["message"]
  }

  date {
    source_field = "time"
    target_field = "dtime"
    source_time_format = "UNIX"
    target_time_format = "yyyy-MM-dd HH:mm:ss"
  }

  date {
    source_field = "time"
    target_field = "dt"
    source_time_format = "UNIX"
    target_time_format = "yyyy-MM-dd"
  }

  # If you would like to get more information about how to configure waterdrop and see full list of filter plugins,
  # please go to https://interestinglab.github.io/waterdrop/#/zh-cn/configuration/base
}

output {

  # If you want to specify which dataset to be output, please specify source_table_name in each output plugin. The value of source_table_name is the same as previous result_table_name.
  # Also, in default context, you don't need to set source_table_name, the output plugin will output the default dataset.
  clickHouse {
    host = "host:9233"
    clickhouse.socket_timeout = 50000
    database = "db"
    table = "topic"
    username = "user"
    password = "pwd"
    bulk_size = 20000
    retry_codes = [209, 210]
    retry = 3
  }

  # If you would like to get more information about how to configure waterdrop and see full list of output plugins,
  # please go to https://interestinglab.github.io/waterdrop/#/zh-cn/configuration/base
}

```

**Running Command(启动命令)**

start-waterdrop.sh --master local[3] --deploy-mode client --queue qq --appname kafka-ck-topic --config topic.yml

**Error Exception**
[详见附件](https://github.com/InterestingLab/waterdrop/files/4922550/ck.log)

2020-07-15 00:37:53 [Stage 163533:===================================>                 (2 + 1) / 3]
20/07/15 00:38:00 ERROR Executor: Exception in task 1.0 in stage 163533.0 (TID 256980)
java.lang.RuntimeException: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 210, host: host, port: 9233; Connect to host:9233 [host/ip] failed: connect timed out
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.initTimeZone(ClickHouseConnectionImpl.java:91)
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:75)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:58)
	at ru.yandex.clickhouse.BalancedClickhouseDataSource.getConnection(BalancedClickhouseDataSource.java:189)
	at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$1.apply(Clickhouse.scala:172)
	at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$1.apply(Clickhouse.scala:170)

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

**Comment by javalover123** [comment]
[错误日志](https://github.com/InterestingLab/waterdrop/files/4922554/ck.log)

**Comment by RickyHuo** [comment]
**host:9233** 9233 端口通吗？ 需要使用 Http 端口

**Comment by javalover123** [comment]
> **host:9233** 9233 端口通吗？ 需要使用 Http 端口

是通的，之前正常写入的，出现这个错误，然后进程就退出了

**Comment by czwanglei** [comment]
host:9233 能ping通吗、最好用ip     这个是http 端口默认是8123



911303635@qq.com
 
发件人： javalover123
发送时间： 2020-07-15 10:43
收件人： InterestingLab/waterdrop
抄送： Subscribed
主题： [InterestingLab/waterdrop] 写入ck配置了 3次重试，怎么一次进程就挂掉了 (#543)
Waterdrop Version(Waterdrop版本)
1.4.1
Flink or Spark Version(Flink 或者 Spark 版本)
spark-2.4.0-bin-hadoop2.7
Java or Scala Version(Java或者Scala版本)
java 1.8
Waterdrop Config(Waterdrop配置文件)
######
###### This config file is a demonstration of streaming processing in waterdrop config
######
spark {
  # You can set spark configuration here
  # Waterdrop defined streaming batch duration in seconds
  spark.streaming.batchDuration = 5
  # see available properties defined by spark: https://spark.apache.org/docs/latest/configuration.html#available-properties
  spark.app.name = "Waterdrop"
  spark.executor.instances = 2
  spark.executor.cores = 1
[ck.log](https://github.com/InterestingLab/waterdrop/files/4922550/ck.log)
  spark.executor.memory = "1g"
}
input {
  # This is a example input plugin **only for test and demonstrate the feature input plugin**
  kafkaStream {
    topics = "topic"
    result_table_name = "topic_kafka"
    consumer.bootstrap.servers = "host:8082"
    consumer.group.id = "waterdrop-topic"
    consumer.rebalance.max.retries = 100
    consumer.failOnDataLoss = false
  }
  # If you would like to get more information about how to configure waterdrop and see full list of input plugins,
  # please go to https://interestinglab.github.io/waterdrop/#/zh-cn/configuration/base
}
filter {
  json {
    source_field = "raw_message"
    result_table_name = "topic"
  }
  remove {
    source_field = ["message"]
  }
  date {
    source_field = "time"
    target_field = "dtime"
    source_time_format = "UNIX"
    target_time_format = "yyyy-MM-dd HH:mm:ss"
  }
  date {
    source_field = "time"
    target_field = "dt"
    source_time_format = "UNIX"
    target_time_format = "yyyy-MM-dd"
  }
  # If you would like to get more information about how to configure waterdrop and see full list of filter plugins,
  # please go to https://interestinglab.github.io/waterdrop/#/zh-cn/configuration/base
}
output {
  # If you want to specify which dataset to be output, please specify source_table_name in each output plugin. The value of source_table_name is the same as previous result_table_name.
  # Also, in default context, you don't need to set source_table_name, the output plugin will output the default dataset.
  clickHouse {
    host = "host:9233"
    clickhouse.socket_timeout = 50000
    database = "db"
    table = "topic"
    username = "user"
    password = "pwd"
    bulk_size = 20000
    retry_codes = [209, 210]
    retry = 3
  }
  # If you would like to get more information about how to configure waterdrop and see full list of output plugins,
  # please go to https://interestinglab.github.io/waterdrop/#/zh-cn/configuration/base
}

Running Command(启动命令)
start-waterdrop.sh --master local[3] --deploy-mode client --queue qq --appname kafka-ck-topic --config topic.yml
Error Exception
详见附件。
2020-07-15 00:37:53 [Stage 163533:===================================> (2 + 1) / 3]
20/07/15 00:38:00 ERROR Executor: Exception in task 1.0 in stage 163533.0 (TID 256980)
java.lang.RuntimeException: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 210, host: host, port: 9233; Connect to host:9233 [host/ip] failed: connect timed out
at ru.yandex.clickhouse.ClickHouseConnectionImpl.initTimeZone(ClickHouseConnectionImpl.java:91)
at ru.yandex.clickhouse.ClickHouseConnectionImpl.(ClickHouseConnectionImpl.java:75)
at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:58)
at ru.yandex.clickhouse.BalancedClickhouseDataSource.getConnection(BalancedClickhouseDataSource.java:189)
at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$1.apply(Clickhouse.scala:172)
at io.github.interestinglab.waterdrop.output.batch.Clickhouse$$anonfun$process$1.apply(Clickhouse.scala:170)
Screenshots
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

**Comment by javalover123** [comment]
ck的配置没错的，报错之前正常写入ck的，重启waterdrop也能正常写入ck。
我分析了一下，应该是 executorBalanced.getConnection 的时候报错，导致停止了。
这里 val executorConn = executorBalanced.getConnection.asInstanceOf[ClickHouseConnectionImpl]
