### ISSUE TITLE
[Feature] seatunnel/waterdrop集成任务调度工具DolphinScheduler

### ISSUE THREAD

**Issue by garyelephant** [apache/incubator-seatunnel#546]
Waterdrop的朋友们，跟各位说一个好消息：

之前很多朋友提出来，希望Waterdrop具备**任务管理和调度**功能，这是一个非常常用的场景。

DolphinScheduler 是国内易观数据公司在2018年开源，2019年进入Apache项目的分布式调度工具，
近期我们社区的一位朋友（感谢@xsbai），正在做将Waterdrop集成到DolphinScheduler。

未来朋友们可以直接在DolphinScheduler上完成任务的调度，Waterdrop变得更强大啦。希望它能帮各位找到更多的应用场景。

DolphinScheduler官网：https://dolphinscheduler.apache.org/en-us/

Waterdrop集成到DolphinScheduler的PR：https://github.com/apache/incubator-dolphinscheduler/pull/3073

**Comment by garyelephant** [comment]
此ISSUE会持续跟进最新进展

**Comment by garyganyang** [comment]
加油

**Comment by garyelephant** [comment]
> 你提交的PR, Some checks were not successful, 快去看看呢?

@xsbai

**Comment by xsbai** [comment]
> > 你提交的PR, Some checks were not successful, 快去看看呢?
> 
> @xsbai

我收到邮件了……但上去一看莫名其名又通过了……应该没什么问题了

**Comment by garyelephant** [comment]
跟进：
代码已经merge到dev分支，目前DolphinScheduler  v1.3.3 版本还没有merge dev分支，估计要到v1.3.4才发布集成waterdrop。

**Comment by zxbing** [comment]
DolphinScheduler v1.3.4依旧没有集成waterdrop

**Comment by tianhanfangyan** [comment]
希望merge到v1.3.7了

**Comment by zxbing** [comment]
cool

David ***@***.***> 于2021年10月12日周二 下午6:48写道：
