### ISSUE TITLE
V2插件放到plugins下无法实例化

### ISSUE THREAD

**Issue by lueric123** [apache/incubator-seatunnel#553]
Waterdrop Version(Waterdrop版本)

waterdrop-2.0.0

Flink or Spark Version(Flink 或者 Spark 版本)
spark2.3.0

Java or Scala Version(Java或者Scala版本)

1.8

把打包好的jar 放到  plugins/我的插件名/lib下
启动./start-waterdrop-spark.sh  --master yarn --deploy-mode client  --config ../config/test.conf
正常加载jar
报错
![image](https://user-images.githubusercontent.com/21017454/88148286-f5a5c600-cc30-11ea-8b81-b9c3a419fdac.png)

**Comment by RickyHuo** [comment]
@lueric123  V2 暂未实现插件加载
