### ISSUE TITLE
本地运行无问题，打包报错，求助！！！

### ISSUE THREAD

**Issue by ocean-zhc** [apache/incubator-seatunnel#605]
本地运行结果如下图，可以正常运行
![image](https://user-images.githubusercontent.com/46189785/106544470-8e9f8d00-6542-11eb-9658-4c83d8c24e0d.png)
整体打包，提示下图错误，不解
![image](https://user-images.githubusercontent.com/46189785/106544542-ae36b580-6542-11eb-896d-372490240f1b.png)

**Comment by zhanghaicheng1** [comment]
sbt版本1.4.7
![image](https://user-images.githubusercontent.com/46189785/106544688-ec33d980-6542-11eb-8e72-6ae5f7ab3eca.png)
scala版本：2.11.8
