### ISSUE TITLE
[Feature] Waterdrop 集成任务调度工具 Airflow

### ISSUE THREAD

**Issue by sunhailin-Leo** [apache/incubator-seatunnel#619]
* 基于 Airflow 开发的 Waterdrop 插件。https://github.com/sunhailin-Leo/airflow-waterdrop-plugin
* 目前适配的 Airflow 版本为 `1.10.12`, Waterdrop 版本为 `1.X`.

**Comment by sunhailin-Leo** [comment]
* 目前线上已使用自行开发的 operator 运行每日 Hive 分区表 To Clickhouse 的同步任务。

**Comment by garyelephant** [comment]
@sunhailin-Leo 真棒，大家都能用上了

**Comment by sunhailin-Leo** [comment]
> @sunhailin-Leo 真棒，大家都能用上了

* 目前支持的部分还很有限，可以一起讨论一起改进 😄
