### ISSUE TITLE
[FEATURE REQUEST] Spark 3 support

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-seatunnel#651]
**1. Waterdrop Version(Waterdrop版本)**

**2. 你希望增加什么功能？请尽可能详细描述**

**3. 以上新功能的使用场景？**

**4. Additional Context Information /  其他附加信息（如有）**

**Comment by garyelephant** [comment]
@pan3793 感谢你的建议，目前正在做关于Spark3，hadoop3的支持，近期会release，敬请期待。

**Comment by DavidZ1** [comment]
包含支持 Spark 3 读取 Hadoop EC 文件吗？

**Comment by garyelephant** [comment]
duplicate of #948

**Comment by zyd915** [comment]
Seatunnel对Hadoop3的支持
https://bolder-gasoline-6e0.notion.site/Seatunnel-Hadoop3-dc8568d60486458792881974aa93b635
