### ISSUE TITLE
[Feature][community] Add chat room after become Apache incubator

### ISSUE THREAD

**Issue by zhongjiajie** [apache/incubator-seatunnel#705]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

ref: https://github.com/InterestingLab/seatunnel/pull/699#issuecomment-974661969  we should add chat room after we in apache incubator

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
If you start to do it, please let me know and I will provide you with some help

**Comment by zhongjiajie** [comment]
Got it.

**Comment by zhongjiajie** [comment]
> If you start to do it, please let me know and I will provide you with some help

@CalvinKirs It is already in Apache incubator, have could I do next steps.

**Comment by CalvinKirs** [comment]
> > If you start to do it, please let me know and I will provide you with some help
> 
> @CalvinKirs It is already in Apache incubator, have could I do next steps.

Wait for the code transfer to complete

**Comment by zhongjiajie** [comment]
Close it, cause we already add it to https://github.com/apache/incubator-seatunnel#contact-us
