### ISSUE TITLE
[DISCUSS][ALL] Adjust project structure

### ISSUE THREAD

**Issue by zixi0825** [apache/incubator-seatunnel#736]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I don't think we should put too many plugin modules in the top-level directory，In my opinion, it can be adjusted into the following structure：
- seatunnel-common
- seatunnel-config
- seatunnel-dist
- seatunnel-server ：Corresponding to the content of the seatunnel-core, it is responsible for the startup of the application
- seatunnel-spi：Corresponding to the seatunnel-apis, the main content is the basic interface
- seatunnel-spark-engine/runtime（choose one）
    - seatunnel-spark-api
    - seatunnel-spark-plugins
        - seatunnel-spark-plugin-jdbc
- seatunnel-spark2-engine/runtime
    - seatunnel-spark2-api
    - seatunnel-spark2-plugins
        - seatunnel-spark2-plugin-jdbc
- seatunnel-flink112-engine/runtime
    - seatunnel-flink112-api
    - seatunnel-flink112-plugins
        - seatunnel-flink112-plugin-jdbc

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jon-qj** [comment]
+1

**Comment by yx91490** [comment]
1. change is too big if you only want to "not put plugin modules in the top-level directory".
2. why rename seatunnel-apis to seatunnel-spi but retain seatunnel-spark-api and seatunnel-flink112-api?
3. what's the differences between seatunnel-spark-engine and seatunnel-spark2-engine?
4. Should every new engine need new bootstrap script and new api module and new plugin implementations? 
5. seatunnel-config can be replaced with dependency.

**Comment by simon824** [comment]
IMO, move seatunnel-spark2-api/plugin under  seatunnel-spark-engine is better.

**Comment by garyelephant** [comment]
@zixi0825 Thanks for your advice，I'm also thinking about this recently. Currently we are reviewing the codes of v2 branch, we can continue talking about this these days. After the decision have been made, then we can make some changes.

**Comment by garyelephant** [comment]
project structure has already been changed, so we close this issue, if you have any further more idea, please reopen this
