### ISSUE TITLE
[Feature][Plugin] Introduce hudi

### ISSUE THREAD

**Issue by simon824** [apache/incubator-seatunnel#759]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

- plugin-spark-source-hudi
- plugin-spark-sink-hudi
- plugin-flink-source-hudi
- plugin-flink-sink-hudi

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by timothy1024** [comment]
hi @simon824, you can split this feature to several steps, so others can work together. 😃

**Comment by simon824** [comment]
> hi @simon824, you can split this feature to several steps, so others can work together. 😃

Sounds good, i planned to achieve these four plugins one by one, welcome to complete it together.
- plugin-spark-source-hudi
- plugin-spark-sink-hudi
- plugin-flink-source-hudi
- plugin-flink-sink-hudi

**Comment by dailidong** [comment]
> > hi @simon824, you can split this feature to several steps, so others can work together. 😃
> 
> Sounds good, i planned to achieve these four plugins one by one, welcome to complete it together.
> 
> * plugin-spark-source-hudi
> * plugin-spark-sink-hudi
> * plugin-flink-source-hudi
> * plugin-flink-sink-hudi

good job, I think you can submit four new sub-issues for this Feature, then make an association in this issue, you can refer to this one[1]

1: https://github.com/apache/dolphinscheduler/issues/6963

**Comment by simon824** [comment]
> > > hi @simon824, you can split this feature to several steps, so others can work together. 😃
> > 
> > 
> > Sounds good, i planned to achieve these four plugins one by one, welcome to complete it together.
> > 
> > * plugin-spark-source-hudi
> > * plugin-spark-sink-hudi
> > * plugin-flink-source-hudi
> > * plugin-flink-sink-hudi
> 
> good job, I think you can submit four new sub-issues for this Feature, then make an association in this issue, you can refer to this one[1]
> 
> 1: [apache/dolphinscheduler#6963](https://github.com/apache/dolphinscheduler/issues/6963)

Got it.

**Comment by choucmei** [comment]
please split this feature ,i'm interested in hudi, I want to contribute to this.
