### ISSUE TITLE
[Feature][UT] add unit test

### ISSUE THREAD

**Issue by yx91490** [apache/incubator-seatunnel#783]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

we'll adjust project structure in roadmap #720 , but currently we lack unit test to make sure the adjustments didn't bring bugs.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yx91490** [comment]
at the same time, to make code more robust, how about let a pr to be merged after it got 2 valid votes and stay for 1 day for no negative votes.

**Comment by dailidong** [comment]
> at the same time, to make code more robust, how about let a pr to be merged after it got 2 valid votes and stay for 1 day for no negative votes.

good suggestion, I think 1 valid vote will be OK because we can't find enough reviewer to check the PR .  we need more contributors to add UT

**Comment by xbkaishui** [comment]
I will do it

**Comment by yx91490** [comment]
> I will do it

welcome, I think you can make s new issue with an explicit module to contribute to.

**Comment by JesseAtSZ** [comment]
I will do it
