### ISSUE TITLE
Please translate the FAQ into English

### ISSUE THREAD

**Issue by dailidong** [apache/incubator-seatunnel#784]
Please translate the FAQ into English
the FAQ issue are as follows, https://github.com/InterestingLab/seatunnel/issues/267

**Comment by yx91490** [comment]
where to put the doc? just create another issue or add it to code repository?

**Comment by dailidong** [comment]
> where to put the doc? just create another issue or add it to code repository?

you can submit a PR to `https://github.com/InterestingLab/seatunnel-docs` root directory, named `FAQ.md`

**Comment by yx91490** [comment]
> > where to put the doc? just create another issue or add it to code repository?
> 
> you can submit a PR to `https://github.com/InterestingLab/seatunnel-docs` root directory, named `FAQ.md`

OK, I want to do this.

**Comment by yx91490** [comment]
@wolfboys which directory do you think I should put the FAQ documents under the website project?

**Comment by dailidong** [comment]
> @wolfboys which directory do you think I should put the FAQ documents under the website project?

please put the doc to this dir `https://github.com/apache/incubator-seatunnel-website/tree/main/docs`, happy new year

**Comment by yx91490** [comment]
PR: https://github.com/apache/incubator-seatunnel-website/pull/46

**Comment by wolfboys** [comment]
@dailidong LGTM. please PTAL.

**Comment by CalvinKirs** [comment]
done
