### ISSUE TITLE
[Feature][sql] Add write to mysql by using sql template in Dockerfile

### ISSUE THREAD

**Issue by leo65535** [apache/incubator-seatunnel#801]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add write to mysql by using sql template in Dockerfile.

For more detail, please go to https://github.com/InterestingLab/seatunnel/issues/716

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xleoken** [comment]
Closing this issue first, open it when necessary.
