### ISSUE TITLE
[Feature][plugin-spark-output-clickhouse] DateTime/Date Column support Timestamp

### ISSUE THREAD

**Issue by RickyHuo** [apache/incubator-seatunnel#851]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When inserting data into ClickHouse with DateTime or Date column must convert data into string data with a specified format. If the plugin can insert from Spark Timestamp column would be better.

当前写入 ClickHouse 中 DateTime/Date 列时，必须将对应字段转换为指定格式字符串（yyyy-MM-dd），如果支持通过 Spark 中的 Timestamp 就能够写入DateTime/Date的话最好了。

### Usage Scenario

data synchronization

### Related issues

#848 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kyle-cx91** [comment]
@RickyHuo @garyelephant @CalvinKirs 
Hey guys, I have review the code of spark-clickhouse-sink connector, and I'd like to challenge this issue

**Comment by CalvinKirs** [comment]
> @RickyHuo @garyelephant @CalvinKirs Hey guys, I have review the code of spark-clickhouse-sink connector, and I'd like to challenge this issue

looking forward :)
