### ISSUE TITLE
[Feature][plugin-filter-date] Date filter supports Timestamp

### ISSUE THREAD

**Issue by RickyHuo** [apache/incubator-seatunnel#852]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The filter of Date supports convert from `Timestamp`

### Usage Scenario

date {
    source_field = "timestamp_field"
    target_field = "date"
    source_time_format = "TIMESTAMP"
    target_time_format = "yyyy/MM/dd"
}

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dongzl** [comment]
I want to try it.

**Comment by kezhenxu94** [comment]
@dongzl thanks. assigned to you. Good luck!

**Comment by dailidong** [comment]
good job
