### ISSUE TITLE
[Feature][Chore] Change organization name and verify all related link

### ISSUE THREAD

**Issue by zhongjiajie** [apache/incubator-seatunnel#856]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We should change content related to organization from `InterestingLab` to `apache` and verify all related link to ASF.
Such as `# seatunnel [![Build Status](https://travis-ci.org/InterestingLab/seatunnel.svg?branch=master)](https://travis-ci.org/InterestingLab/seatunnel)` in Readme file

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
I would start it after we migration to Apache organization

**Comment by yx91490** [comment]
It's time to do it :)

**Comment by zhongjiajie** [comment]
> It's time to do it :)

Thanks for your feedback
