### ISSUE TITLE
[Feature][README] Modify the document address in README.md and README_zh_CN.md

### ISSUE THREAD

**Issue by wuchunfu** [apache/incubator-seatunnel#873]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

 Modify the document address in `README.md` and `README_zh_CN.md`

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by garyelephant** [comment]
what does this mean ?

**Comment by wuchunfu** [comment]
Modify the document addresses involved in the readme. I will do this work after the 2.x-related directories in the official documentation website are available.
