### ISSUE TITLE
[Feature][config] improve the config parse logic

### ISSUE THREAD

**Issue by leo65535** [apache/incubator-seatunnel#904]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

**This sub issue focus on solving the parse logic**

- Change path token separator from "." to "->"".
- Added parseObjectForseatunnel() to parse config objects in input, filter, output for seatunnel.

👉 **Change 1** : Change path token separator from "." to "->"".

`config` always let the key as path if the key contains `.`, like following

```
sink {
  a.b.c.Console {}
}
```

equivalent to

```
sink {
  a {
    b {
      c {
        Console {}
      }
    }
  }
}
```

In fact, it's not recommend to make these changes, because JSON keys should be enclosed in double quotes, so we can revert these changes.

👉 **Change 2** : parseObjectForseatunnel().

The main login of `parseObjectForseatunnel` is to parse config objects in `sources`, `transforms`, `sinks` for seatunnel.

We can move these changes out of `config`, and move them to `ConfigBuilder`

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leo65535** [comment]
cc @garyelephant @CalvinKirs @simon824, I had rewrite the logic and raise a draft pull request, it will help to understand my statement.

**Comment by simon824** [comment]
Great job ! I'm ok with these two changes, and I will test more cases later.

**Comment by RickyHuo** [comment]
I have saw the draft PR. The seatunnel-config has been replaced with typesafe config.

The reason why we develop seatunnel-config base on typesafe config is that the plugin order of parsed Config is not the same as our configuration when transform section has multiply plugins.

The origin issue is #29, I'm sorry I forget config test at that moment.

We should test those demo:

```
source {
	
}

transform {
	
	sql {
		sql = "sql1"
	}

	sql {
		sql = "sql2"
	}

	sql {
		sql = "sql3"
	}
}

sink {
	
}

```


```
source {
	
}

transform {
	
	sql {
		sql = "sql1"
	}

	json {
		source_field = "xxx"
	}

	sql {
		sql = "sql3"
	}
}

sink {
	
}

```

**Comment by leo65535** [comment]
> our configuration when transform section has multiply plugins.

Thanks for the warning, and that's a real problem. Let me think.

**Comment by leo65535** [comment]
Hi @RickyHuo @garyelephant @CalvinKirs, I implemented the second version, please review the patch when you are free, thanks.

1. Add `SeaTunnelConfigFactory` which works as `ConfigFactory`.
2. Extract the sort logic to `SeaTunnelConfigParser`(Keep it the same as before)

![image](https://user-images.githubusercontent.com/95013770/147808199-9222f532-47a0-4eeb-bf09-36e3e5f63414.png)

**Comment by garyelephant** [comment]
> Hi @RickyHuo @garyelephant @CalvinKirs, I implemented the second version, please review the patch when you are free, thanks.
> 
> 1. Add `SeaTunnelConfigFactory` which works as `ConfigFactory`.
> 2. Extract the sort logic to `SeaTunnelConfigParser`(Keep it the same as before)
> 
> ![image](https://user-images.githubusercontent.com/95013770/147808199-9222f532-47a0-4eeb-bf09-36e3e5f63414.png)

@leo65535 thanks for your contribution, can you briefly explain how to implement the config parsing logic to keep the order as in config file?

**Comment by leo65535** [comment]
> can you briefly explain how to implement the config parsing logic to keep the order as in config file?

I move your changes to `SeaTunnelConfigParser`.
