### ISSUE TITLE
[License] check dependencies' binary licenses

### ISSUE THREAD

**Issue by kezhenxu94** [apache/incubator-seatunnel#905]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently https://github.com/apache/incubator-seatunnel/blob/dev/tools/dependencies/known-dependencies.txt takes no effect, we have bad case like #855 that doesn't address the new dependencies `jcommander` correctly. We need to find a way to address this case.

### Usage Scenario

Dependencies should be checked although they were packed into a fat jar

### Related issues

#jcommand

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kezhenxu94** [comment]
@CalvinKirs are you interested in working this with me together?

**Comment by CalvinKirs** [comment]
> @CalvinKirs are you interested in working this with me together?

Very honored~
The current dep-license file is not perfect, and there is no check mechanism at the same time. I don't know how to check the shade package license.

**Comment by CalvinKirs** [comment]
I may need to spend some time looking at how other projects are done

**Comment by kezhenxu94** [comment]
The problem now is that we don't have a list of the dependencies, once we got the list, we can reuse the script https://github.com/apache/dolphinscheduler/blob/dev/tools/dependencies/check-LICENSE.sh

Even we can have the dependencies from final .tgz, we can have another command to copy the dependencies that this project uses, like 

```shell
./mvnw dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=/tmp/seatunnel-dependencies
```

So we can generate the same file `third-party-dependencies.txt` like the one in https://github.com/apache/dolphinscheduler/blob/dev/tools/dependencies/check-LICENSE.sh , with


```shell
ls /tmp/seatunnel-dependencies > third-party-dependencies.txt
```

then everything else is the same as https://github.com/apache/dolphinscheduler/blob/dev/tools/dependencies/check-LICENSE.sh

**Comment by CalvinKirs** [comment]
> The problem now is that we don't have a list of the dependencies, once we got the list, we can reuse the script https://github.com/apache/dolphinscheduler/blob/dev/tools/dependencies/check-LICENSE.sh
> 
> Even we can have the dependencies from final .tgz, we can have another command to copy the dependencies that this project uses, like
> 
> ```shell
> ./mvnw dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=/tmp/seatunnel-dependencies
> ```
> 
> So we can generate the same file `all-dependencies.txt` like the one in https://github.com/apache/dolphinscheduler/blob/dev/tools/dependencies/check-LICENSE.sh , with
> 
> ```shell
> ls /tmp/seatunnel-dependencies > all-dependencies.txt
> ```
> 
> then everything else is the same as https://github.com/apache/dolphinscheduler/blob/dev/tools/dependencies/check-LICENSE.sh

deeply thanks~ let me try do this
