### ISSUE TITLE
类似的项目datatunnel，可以相互学习一下好的经验

### ISSUE THREAD

**Issue by melin** [apache/incubator-seatunnel#921]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

也开发了一个基于spark 同步项目datatunnel，之前不了解seatunnel。以后可以相互学习改进：
https://github.com/melin/datatunnel

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by garyelephant** [comment]
@melin good project, please feel free to contribute to SeaTunnel if you are willing to do this.

**Comment by wuchunfu** [comment]
Please modify the title and description information to English, thanks.
