### ISSUE TITLE
[Feature][Module Name] Apache Druid Source Plugin

### ISSUE THREAD

**Issue by asdf2014** [apache/incubator-seatunnel#922]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

# Source plugin: Druid

## Description

Read data from Apache Druid.

## Options

| name            | type           | required | default value |
| --------------- | -------------- | -------- | ------------- |
| jdbc_url        | `String`       | yes      | -             |
| datasource      | `String`       | yes      | -             |
| start_timestamp | `Long`         | no       | -             |
| end_timestamp   | `Long`         | no       | -             |
| columns         | `List<String>` | no       | `*`           |

### jdbc_url [`String`]

The URL of JDBC of Apache Druid.

### datasource [`String`]

The DataSource name in Apache Druid.

### start_timestamp [`Long`]

The start timestamp of DataSource.

### end_timestamp [`Long`]

The end timestamp of DataSource.

### columns [`List<String>`]

These columns that you want to query of DataSource.

### common options [string]

Source Plugin common parameters, refer to [Source Plugin](./source-plugin.md) for details

## Example

```bash
druid {
    jdbc_url = "jdbc:avatica:remote:url=http://localhost:8082/druid/v2/sql/avatica/"
    datasource = "wikipedia"
    start_timestamp = 1464710400
    end_timestamp = 1467302400
    columns = ["flags","page"]
}
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by garyelephant** [comment]
@asdf2014 please feel free to submit your PR, also don't forget to add documents

**Comment by asdf2014** [comment]
Hi, @garyelephant . I just submitted the related PR and linked it to this issues, please take a look, thanks a lot.
