### ISSUE TITLE
[Bug] [config] Can not resolve variables.

### ISSUE THREAD

**Issue by leo65535** [apache/incubator-seatunnel#924]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Conf
```
filter {

  sql {
    table_name = "user_view"
    sql = "select '"${city2}"'"
    result_table_name = "result1"
  }

  sql {
    table_name = "user_view"
    sql = "select '"${dt}"'"
    result_table_name = "result2"
  }
}
```

### org.apache.seatunnel.config.CompleteTests

```

public static void main(String[] args) {

  System.out.println("Hello World");
  System.setProperty("dt", "20190318");
  System.setProperty("city2", "shanghai");

  CompleteTests completeTests = new CompleteTests();
  Config config = ConfigFactory.parseFile(completeTests.getFileFromResources("seatunnel/variables.conf"));
  config = config.resolve(ConfigResolveOptions.defaults().setAllowUnresolved(true))
    .resolveWith(ConfigFactory.systemProperties(), ConfigResolveOptions.defaults().setAllowUnresolved(true));

  ConfigRenderOptions renderOptions = ConfigRenderOptions.defaults().setComments(false).setOriginComments(false);
  System.out.println(config.root().render(renderOptions));
    
}
```

### Result

![image](https://user-images.githubusercontent.com/95013770/147868248-0a94c3e0-c8c8-471c-9841-00e356f901e9.png)

### Analyze

There is a bug between `dev` and `1faf2e`.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by garyelephant** [comment]
@leo65535 did you mean that codes in dev branch have a bug of failing to parse variable substitution? why you compare dev branch with commit `1faf2e` ?

**Comment by leo65535** [comment]
hi @garyelephant, I use git history for `CompleteTests` file.

![image](https://user-images.githubusercontent.com/95013770/147998599-8bdfaa23-f27d-4136-a144-384acbf5adc5.png)

**Comment by leo65535** [comment]
And, I also found the commit of the problem, it is `5c44cb64`

**Comment by leo65535** [comment]
fixed at https://github.com/apache/incubator-seatunnel/pull/906
