### ISSUE TITLE
[Bug] [Doc] Seatunnel 2.0.0-pre release package not found

### ISSUE THREAD

**Issue by chenshuai1995** [apache/incubator-seatunnel#943]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When i start seatunnel whith quick start document, the seatunnel download packege link is not found. I cannot download the seatunnel package following the document.

### SeaTunnel Version

v2.0.0-pre

### SeaTunnel Config

```conf
None
```

### Running Command

```shell
None
```

### Error Exception

```log
➜  ~ wget https://github.com/InterestingLab/seatunnel/releases/download/v2.0.0-pre/seatunnel-dist-2.0.0-pre-2.11.8-release.zip -O seatunnel-2.0.0.zip
--2022-01-04 09:49:31--  https://github.com/InterestingLab/seatunnel/releases/download/v2.0.0-pre/seatunnel-dist-2.0.0-pre-2.11.8-release.zip
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/apache/incubator-seatunnel/releases/download/v2.0.0-pre/seatunnel-dist-2.0.0-pre-2.11.8-release.zip [following]
--2022-01-04 09:49:31--  https://github.com/apache/incubator-seatunnel/releases/download/v2.0.0-pre/seatunnel-dist-2.0.0-pre-2.11.8-release.zip
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 404 Not Found
2022-01-04 09:49:32 ERROR 404: Not Found.
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RickyHuo** [comment]
@chenshuai1995  https://github.com/apache/incubator-seatunnel/releases/download/v2.0.0-pre/waterdrop-dist-2.0.0-alpha-2.11.8-release.zip
