### ISSUE TITLE
[Bug] [Module Name] Bug titlemysql8驱动问题

### ISSUE THREAD

**Issue by ch0shim** [apache/incubator-seatunnel#979]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

在hive数据同步到clickhouse时，我的hive元数据服务存储用的mysql8.x，在我将8.0的连接驱动加载到st后，又报了：
Caused by :java.sql.SqlException: unknown system variable 'tx_isolation'

### SeaTunnel Version

1.5.7

### SeaTunnel Config

```conf
hive -> clickhouse常规配置
```

### Running Command

```shell
./start-seatunnel.sh --master yarn --deploy-mode cluster --config ../config/....
```

### Error Exception

```log
Caused by :java.sql.SqlException: unknown system variable 'tx_isolation'
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yx91490** [comment]
can you provide your config file?

**Comment by CalvinKirs** [comment]
For better communication, please describe your problem in English, I will close this issue, you can reopen it when you are done update.
