### ISSUE TITLE
[Bug] [seatunnel-config] PathParser PathParser.parsePath(path) ，Parsing path wrong

### ISSUE THREAD

**Issue by felix-thinkingdata** [apache/incubator-seatunnel#996]
When running flink local debugging, the following error will be reported because PathParser was overwritten. Is this compatible

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/59079269/148764984-a0c9cd0f-6a6e-44f0-ba94-3bcbeb5f7acc.png)
This is a normal result

![image](https://user-images.githubusercontent.com/59079269/148765219-868871b6-bfb1-4395-a3f4-4e1a4bd6ea8a.png)
This is what we have now.

![image](https://user-images.githubusercontent.com/59079269/148767102-0cf3e88a-e72c-41b1-a68a-6c1ff6fcae71.png)

### SeaTunnel Version

dev 

### SeaTunnel Config

```conf
com.typesafe.config.ConfigException$Missing: No configuration setting found for key '"akka.remote.netty.tcp.maximum-frame-size"'
```

### Running Command

```shell
com.typesafe.config.ConfigException$Missing: No configuration setting found for key '"akka.remote.netty.tcp.maximum-frame-size"'
```

### Error Exception

```log
com.typesafe.config.ConfigException$Missing: No configuration setting found for key '"akka.remote.netty.tcp.maximum-frame-size"'
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leo65535** [comment]
hi @felix-thinkingdata, we can close this issue. Fixed at https://github.com/apache/incubator-seatunnel/pull/1005
